# Generated by Django 5.1.3 on 2024-11-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
            ],
            options={
                'ordering': ['start_at', 'end_at'],
                'unique_together': {('start_at', 'end_at')},
            },
        ),
    ]
